# @package _global_

protagonist:
  name: sac
  _target_: agent.sac.SAC
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later

  critic_cfg: ${protagonist_q_net}
  actor_cfg: ${protagonist_diag_gaussian_actor}
  init_temp: 1e-2 # use a low temp for IL

  soft_update: True

  alpha_lr: 3e-4
  alpha_betas: [0.9, 0.999]

  actor_lr: 3e-5
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1

  critic_lr: 3e-4
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: 1
 
  # learn temperature coefficient (disabled by default)
  learn_temp: false

  # Use either value_dice actor or normal SAC actor loss
  vdice_actor: false

protagonist_q_net:
  _target_: agent.sac_models.DoubleQCritic
  obs_dim: ${protagonist.obs_dim}
  action_dim: ${protagonist.action_dim}
  hidden_dim: 256
  hidden_depth: 2

protagonist_diag_gaussian_actor:
  _target_: agent.sac_models.DiagGaussianActor
  obs_dim: ${protagonist.obs_dim}
  action_dim: ${protagonist.action_dim}
  hidden_dim: 256
  hidden_depth: 2
  log_std_bounds: [-5, 2]